# localoptimg.jl
# Functions for frequentist optimization 

"""
    define_objective_function(
        data::OrderedDict, 
        simulator::Function,
        lossfun::Function
    )::Function
  

Define an objective function based on `data`, `simulator`, `lossfun`. <br>
`simulator` and `lossfun` are assumed to be generated by `define_fitting_simulator` 
and `define_loss_function`, respectively.
"""
function define_objective_function(
    data::OrderedDict, 
    simulator::Function,
    lossfun::Function
    )::Function


    function objective_function(pvec; kwargs...)::Float64

        sim = simulator(pvec; kwargs...) 
        l = lossfun(data, sim)

        return l
    end

    return objective_function
end


function define_objective_function(f::PMCBackend)

    return define_objective_function(
        f.data, 
        f.simulator,
        f.loss 
    )

end